#!/bin/bash

G_DESIGN_SCRIPT="./designScript.sh"
G_DESIGN_TAGS="-f"
G_DESIGN_CONFIG_FILE="conf/designConfig.conf"
G_DESIGN_INPUT_FILE="../../output/1-recipe_program/docs/idee.txt"

G_ISSUE_SCRIPT="./issueScript.sh"
G_ISSUE_TAGS="-g"
G_DESIGN_FILE="../../output/1-recipe_program/docs/design_doocument_raw_temp.txt"
G_ISSUE_RAW_TAGS="-fi"
G_ISSUE_CONFIG_FILE="conf/issueConfig.conf"
G_RAW_ISSUE_FILE="../../output/1-recipe_program/docs/raw_issues.txt"
G_ISSUE_OPEN_TAGS="-fo"
G_OPEN_ISSUE_FILE="../../output/1-recipe_program/docs/issues_open.txt"

G_COMMIT_SCRIPT="./commitScript.sh"
G_COMMIT_TAGS="-gi"
G_COMMIT_CONFIG_FILE="conf/commitConfig.conf"

#struct
G_COMMIT_FORMAT_STRUCT_TAGS="-fs"
G_COMMIT_FORMAT_CONFIG_FILE="conf/formatStructure.conf"

#file
#G_COMMIT_FORMAT_STRUCT_TAGS="-fc"
#G_COMMIT_FORMAT_CONFIG_FILE="conf/formatFile.conf"
