#!/bin/bash

G_SCRIPT="./ollamaScript.sh"
G_SCRIPT_TAG="-pf"
G_LLM_CONF="conf/ollamaConfig_code.conf"
G_MODEL_CONF="model/conf/commitCodeGiven.conf"
OPEN_ISSUE_FILE="../../output/1-recipe_program/docs/issues_open.txt"
TEMP_COMMIT_FILE="../../output/1-recipe_program/docs/temp_commit.txt"

ISSUE_FILE="../../output/1-recipe_program/docs/issues_open.txt"
RESOLVED_TAKS="../../output/1-recipe_program/docs/resolved_plan.txt"

MESSAGE_HISTORY="../../output/1-recipe_program/docs/message_history.txt"
#./ollamaScript.sh -pf conf/ollamaConfig.conf model/conf/commit.conf ../../output/1-recipe_program/docs/issues_open.txt
