#!/bin/bash

G_SCRIPT="./ollamaScript.sh"
G_SCRIPT_TAG="-pfc"
G_LLM_CONF="conf/ollamaConfig.conf"
G_MODEL_CONF="model/conf/commit.conf"
OPEN_ISSUE_FILE="../../output/1-recipe_program/docs/issues_open.txt"
TEMP_COMMIT_FILE="../../output/1-recipe_program/docs/temp_commit.txt"

#./ollamaScript.sh -pf conf/ollamaConfig.conf model/conf/commit.conf ../../output/1-recipe_program/docs/issues_open.txt
