#!/bin/bash

TEMP_FORMAT_FILE="../../output/1-recipe_program/docs/temp_structure.txt"

#./commitScript.sh -fpa conf/commitAllCodeConfig.conf
#./ollamaScript.sh -pf conf/ollamaConfig.conf model/conf/commit.conf ../../output/1-recipe_program/docs/issues_open.txt
