#!/bin/bash

CHECKVAR="dockerConfig is loaded."
SCRIPT_PATH="scripts"
DOCKER_PATH="docker"
#DOCKER_IMAGE_NAME="0-primer"
#DOCKER_IMAGE_NAME="1-sigil"
DOCKER_IMAGE_NAME="2-lexicon"
#DOCKER_CONTAINER_NAME="0-primer"
#DOCKER_CONTAINER_NAME="1-sigil"
DOCKER_CONTAINER_NAME="2-lexicon"
