#!/bin/bash

G_SCRIPT="./ollamaScript.sh"
G_SCRIPT_TAG="-pf"
G_LLM_CONF="conf/ollamaConfig_code.conf"
G_MODEL_CONF="model/conf/fileFormat.conf"
TEMP_COMMIT_FILE="../../output/1-recipe_program/docs/temp_commit.txt"
TEMP_FORMAT_FILE="../../output/1-recipe_program/docs/temp_structure.txt"
FS_CONF="conf/formatStructure.conf"

#XXX./ollamaScript.sh -pf conf/ollamaConfig.conf model/conf/commit.conf ../../output/1-recipe_program/docs/issues_open.txt
