#!/bin/bash

G_SCRIPT="./ollamaScript.sh"
G_SCRIPT_TAG="-pf"
G_LLM_CONF="conf/ollamaConfig.conf"
G_MODEL_CONF="model/conf/issueFormat.conf"
RAW_ISSUE_FILE="../../output/1-recipe_program/docs/raw_issues.txt"
ISSUE_FILE="../../output/1-recipe_program/docs/issues.txt"
TEMP_COMMIT_FILE="../../output/1-recipe_program/docs/temp_commit.txt"
