#!/bin/bash

ACTION_FILE="../../output/1-recipe_program/docs/runnerFile.txt"
PROJECT_DIR="../../output/1-recipe_program/src/"
CONTEXT_FILE="TEMP_context.txt"

G_SCRIPT="./ollamaScript.sh"
G_TAG="-pvc"
G_CONF="conf/ollamaConfig_ollama3-1.conf"
G_MODEL_CONF="model/conf/runner.conf"

ERROR_LOG="TEMP_error_log.txt"
