#!/bin/bash

PROJECT_CONFIG="conf/projectConfig.conf"
G_SCRIPT="./ollamaScript.sh"
G_SCRIPT_TAG="-pvc"
G_LLM_CONF="conf/ollamaConfig_ollama3-1.conf"
G_MODEL_CONF="model/conf/projectSetup.conf"
DESIGN_PROMPT_FILE="../../output/1-recipe_program/docs/idee.txt"
DESIGN_FILE="../../output/1-recipe_program/docs/design_document_raw.txt"
