#!/bin/bash

PLAN_FILE="../../output/1-recipe_program/docs/steps.txt"
TEMP_RESOLVED_FILE="../../output/1-recipe_program/docs/resolved_plan.txt"
G_SCRIPT="./ollamaScript.sh"
G_TAG="-pf"
G_LLM_CONF="conf/ollamaConfig_code.conf"
G_MODEL_CONF="model/conf/issuePlanner.conf"
