#!/bin/bash

ISSUE_FILE="../data/open_issues.txt"
PLAN_FILE="../data/plan_file.txt"
G_SCRIPT="./ollamaScript.sh"
G_TAG="-pv"
G_LLM_CONF="../conf/ollamaConfig_ollama3-1.conf"
G_MODEL_CONF="../model/conf/issuePlanner.conf"
