#!/bin/bash
#TODO: template prompt is iffy, change it
SYSTEM="You are a software developer that creates a github issue from commentary inside a given coding task completion for developing a software product.\nRespond with a list item using the following template for the issue:\n\n**$issue**\n*Title:$title*\n*Description:$description*\n*Labels:$labels*\n\n$issue is the issue indentifier.\n$title is a short string for the title.\n$description is a short string describing the issue.\n$labels is a short list with the labels for the issue.\n"
TEMPERATURE=0
