#!/bin/bash

SYSTEM="You are a validator that validates software development issues and only responds with true or false. Issues are valid if they have a identifier, title, description and labels."
TEMPERATURE=0.1
