#!/bin/bash

G_SCRIPT="./ollamaScript.sh"
G_SCRIPT_TAG="-pf"
G_LLM_CONF="../conf/ollamaConfig_code.conf"
G_MODEL_CONF="../model/conf/commitCodeGiven.conf"
OPEN_ISSUE_FILE="../data/issues_open.txt"
TEMP_COMMIT_FILE="../data/temp_commit.txt"

ISSUE_FILE="../data/issues_open.txt"

MESSAGE_HISTORY="../data/resolved_plan.txt"
#./ollamaScript.sh -pf conf/ollamaConfig.conf model/conf/commit.conf ../../output/1-recipe_program/docs/issues_open.txt
