#!/bin/bash

G_SCRIPT="./ollamaScript.sh"
G_SCRIPT_TAG="-pv"
G_LLM_CONF="conf/ollamaConfig_ollama3-1.conf"
G_MODEL_CONF="model/conf/designFormat.conf"
DESIGN_FILE="../../output/1-recipe_program/docs/design_doocument_raw_temp.txt"

