#!/bin/bash

RESOLVED_PLAN="../data/resolved_plan.txt"

G_SCRIPT="./ollamaScript.sh"
G_SCRIPT_TAG="-pf"
G_LLM_CONF="../conf/ollamaConfig_ollama3-1.conf"
G_MODEL_CONF="../model/conf/issueFormat.conf"
RAW_ISSUE_FILE="../data/raw_issues.txt"
ISSUE_FILE="../data/issues.txt"
TEMP_COMMIT_FILE="../data/temp_commit.txt"
