#!/bin/bash

PLAN_FILE="../data/plan_file.txt"
TEMP_RESOLVED_FILE="../data/resolved_plan.txt"
G_SCRIPT="./ollamaScript.sh"
G_TAG="-pv"
G_LLM_CONF="conf/ollamaConfig_ollama3-1.conf"
G_MODEL_CONF="../model/conf/issueTestPlanner.conf"
